[build-system]
requires = [
    "meson>=1.3.2",
    "meson-python",
    "setuptools>=42",
    "wheel",
    "pybind11>=2.6.0",
    "ninja"
]
build-backend = "mesonpy"

[tool.pytest.ini_options]
testpaths = ["python/tests"]
python_files = ["test_*.py"]
addopts = "-v --tb=short"